# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a0ddd90e1fabfe7ef8164e2fb35fc71ae2abf98899f578bd88f3d57bde0d62099c9c7fccad9c5191e0a798d75451a8f186c837fec2717a80f93b720ca9fad47

test:
  secret_key_base: cc35ad33e99572d8b255d4123be0a1a50465ed012c1ec7e0437c7b0f2ea5020f351efda9a7204b7f1adf9317d4a31b6618305101c6c99dfcb72995d86a250ff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
